---
title: "Learn a bit about the phenotype"
output:
  html_notebook: default
date: "05-09-2017"
---


```{r setup, include=TRUE, warning=FALSE}
knitr::opts_knit$set(root.dir=normalizePath('../../'))
knitr::opts_knit$set(warnings = TRUE, include=TRUE, echo=TRUE)
library(tidyverse)
```


## sample information
In `data/Table S1 Sample informationsMar2017.xlsx`, convert the `xlsx` file into `csv`.

Abbreviation for column `Continent`.
- NA=North America and close regions
- CA=Central Asia and close regions
- SA=South Asia
- EA=East Asia and close regions
- EU=Europe

```{r}
info <- read.csv("data/Table_S1_Sample_informationsMar2017.csv")
dim(info)
head(info)
#tail(info)

```

## Count by Country

Note `China` and `Afghanistan` appears twice.

```{r}

fsize = 15
theme_set(theme_grey(base_size = 18))
pl <- ggplot(data=info) +
    geom_bar(aes(x=Country)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1),
          axis.text=element_text(size=fsize),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))
    
pl
```


